# Generated by Django 3.2 on 2021-04-17 08:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shareApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameModel(
            old_name='ShareProfile',
            new_name='UserProfile',
        ),
        migrations.CreateModel(
            name='ShareResult',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shareApi.userprofile')),
                ('alloted_units', models.IntegerField(default=0)),
                ('alloted', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareApi.share')),
            ],
        ),
    ]
