# Generated by Django 3.2 on 2021-04-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareApi', '0002_auto_20210417_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
