# Generated by Django 3.2 on 2021-04-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareApi', '0003_share_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='shareId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
