# Generated by Django 3.2 on 2021-05-17 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shareApi', '0004_share_shareid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareresult',
            name='alloted_units',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='shareresult',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
